name: deploy-lambda
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Deploy code to Lambda
      uses: denzalman/lambda-python-action@v1.0.0
      with:
        lambda_layer_arn: 'arn:aws:lambda:us-east-1:623894182146:layer:pymazda-deps'
        lambda_name: 'pymazda'
        lambda_region: 'us-east-1'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}